### ISSUE TITLE
Dockerize existing CubeViz 1.0.x

### ISSUE THREAD

**Issue by k00ni** [Dockerizing/CubeViz#1]
### TODO
- [x] Only usage of `docker run` and `docker pull` must be necessary
- [x] ~~keep it open to be able to integrate it with DLD later on~~ (removed due not important for the moment)
- [x] make a short test, that CubeViz shows some visualization for each of the test data cubes
- [x] use a beautiful title for each of the knowledge bases (test data cube)

**Comment by k00ni** [comment]
~~**TODO for myself:** Send @GeorgesAlkhouri test data cubes to visualize.~~

**Comment by k00ni** [comment]
Here are a couple of test data cubes. Please add them as knowledge bases into OntoWiki:
- https://github.com/MichaelMartin/ODP-CubeViz/blob/odp/extensions/cubeviz/assets/OW_statistics.ttl
- https://github.com/AKSW/cubeviz.ontowiki/blob/master/assets/mortality.ttl
- https://github.com/AKSW/cubeviz.ontowiki/blob/master/assets/scoreboard.nt

**Comment by GeorgesAlkhouri** [comment]
An exception occurred when the "CubeViz: Analyze DataCube" button has been pressed.  

OntoWiki Log:

```
2015-11-06T14:33:17+01:00 EMERG (0): Erfurt_Store_Adapter_Exception: SPARQL Error: [OpenLink][Virtuoso iODBC Driver][Virtuoso Server]SQ074: Line 18: SP030: SPARQL compiler, line 7: Undefined namespace prefix at 'qb' before '.' () in query:

SELECT DISTINCT ?element

FROM &lt;http://192.168.99.100:8080/DigitalAgendaScoreboardDataCube/&gt;
WHERE {
                    ?element a qb:Observation .
                    ?element qb:dataSet ?dataset .
                    ?element ?dimension ?dimelement .
                    ?element ?measure ?value .
                    ?dataset a qb:DataSet .
                    ?dataset qb:structure ?datastructuredefintion .
                    ?dimensionspecification a qb:ComponentSpecification .
                    ?dimensionpecification qb:dimension ?dimension .
                    ?measurespecification a qb:ComponentSpecification .
                    ?measurespecification qb:measure ?measure .
                }  -> /var/www/libraries/Erfurt/library/Erfurt/Store/Adapter/Virtuoso.php@1060
```

**Comment by k00ni** [comment]
I didn't know about that issue. Is it time consuming to fix that missing `qb` prefix in the SPARQL-query? 

Basically the analyzing area is a little bit f**\* up due Erfurt can't process the queries that are being used. (All analyze queries fail, even they are valid). So please report the error in the CubeViz [issue tracker](https://github.com/AKSW/cubeviz.ontowiki) and if you need more than 1 hour to fix it, please ignore it for now. There are more important things on the agenda.

Despite that error. Is everything else up and running?

**Comment by k00ni** [comment]
To myself: Maybe create an issue in Erfurt about that exception.

**Comment by k00ni** [comment]
Looking good so far. If you think you are finished here, please close this issue.

**Comment by GeorgesAlkhouri** [comment]
done.
